<?php

namespace Database\Seeders;

use App\Models\Academy;
use App\Models\Trial;
use App\Models\User;
use Illuminate\Database\Seeder;

class TrialSeeder extends Seeder
{
    public function run(): void
    {
        $trials = [
            [
                'name' => 'U-14 Cricket Trials Ahmedabad',
                'posted_by_user_id' => 3,
                'academy_id' => 1,
                'organization_name' => 'Elite Cricket Academy',
                'sport_id' => 1,
                'event_datetime' => now()->addDays(14)->toDateTimeString(),
                'venue' => 'Narendra Modi Stadium, Ahmedabad',
                'google_maps_url' => 'https://maps.google.com/?q=Narendra+Modi+Stadium',
                'city_id' => 1,
                'contact_number' => '+91 98765 43210',
                'registration_deadline' => now()->addDays(7)->toDateString(),
                'eligibility' => 'Boys aged 12-14 years\nAhmedabad residents preferred\nBasic cricket knowledge required',
                'entry_fee' => '200',
                'required_documents' => json_encode(['Aadhaar Card', 'Passport Photo']),
                'vacancies' => 30,
                'benefits' => 'Selected athletes get free academy kit and 3-month training access',
                'status' => 'published',
            ],
            [
                'name' => 'U-16 Football Trials Mumbai',
                'posted_by_user_id' => 9,
                'academy_id' => 2,
                'organization_name' => 'Mumbai City FC Academy',
                'sport_id' => 2,
                'event_datetime' => now()->addDays(21)->toDateTimeString(),
                'venue' => 'Cooperage Ground, Mumbai',
                'google_maps_url' => 'https://maps.google.com/?q=Cooperage+Ground',
                'city_id' => 2,
                'contact_number' => '+91 22 2345 6789',
                'registration_deadline' => now()->addDays(14)->toDateString(),
                'eligibility' => 'Boys and girls aged 14-16 years\nOpen to all skill levels\nMust bring own shin guards',
                'entry_fee' => '300',
                'required_documents' => json_encode(['Aadhaar Card', 'School ID', 'Medical certificate']),
                'vacancies' => 25,
                'benefits' => 'Trial kit provided,Top performers get academy scholarships',
                'status' => 'published',
            ],
            [
                'name' => 'Junior Badminton Selection Camp',
                'posted_by_user_id' => 3,
                'academy_id' => 1,
                'organization_name' => 'Ace Badminton Academy',
                'sport_id' => 3,
                'event_datetime' => now()->addDays(10)->toDateTimeString(),
                'venue' => 'Sports Complex, Gandhinagar',
                'google_maps_url' => 'https://maps.google.com/?q=Sports+Complex+Gandhinagar',
                'city_id' => 1,
                'contact_number' => '+91 98250 11111',
                'registration_deadline' => now()->addDays(5)->toDateString(),
                'eligibility' => 'Ages 8-16 years\nBeginners welcome\nBring non-marking shoes',
                'entry_fee' => '150',
                'required_documents' => json_encode(['Aadhaar Card', 'Passport photo']),
                'vacancies' => 40,
                'benefits' => 'Free trial shuttlecocks,Assessment by certified coaches',
                'status' => 'published',
            ],
            [
                'name' => 'Swimming Talent Identification Program',
                'posted_by_user_id' => 3,
                'academy_id' => 1,
                'organization_name' => 'Aqua Swim Academy',
                'sport_id' => 4,
                'event_datetime' => now()->addDays(7)->toDateTimeString(),
                'venue' => 'Olympic Swimming Pool, Ahmedabad',
                'google_maps_url' => 'https://maps.google.com/?q=Olympic+Swimming+Pool',
                'city_id' => 1,
                'contact_number' => '+91 98260 22222',
                'registration_deadline' => now()->addDays(3)->toDateString(),
                'eligibility' => 'Age 6-18 years\nMust be able to swim 25m freestyle\nWater safety test will be conducted',
                'entry_fee' => '100',
                'required_documents' => json_encode(['Aadhaar Card', 'Medical fitness certificate']),
                'vacancies' => 50,
                'benefits' => 'Free swimming cap and goggles for all participants',
                'status' => 'published',
            ],
            [
                'name' => 'Athletics Sprint Trials - Delhi',
                'posted_by_user_id' => 3,
                'academy_id' => null,
                'organization_name' => 'Delhi Athletics Club',
                'sport_id' => 5,
                'event_datetime' => now()->addDays(18)->toDateTimeString(),
                'venue' => 'Jawaharlal Nehru Stadium, Delhi',
                'google_maps_url' => 'https://maps.google.com/?q=Jawaharlal+Nehru+Stadium',
                'city_id' => 3,
                'contact_number' => '+91 98111 33333',
                'registration_deadline' => now()->addDays(12)->toDateString(),
                'eligibility' => 'Track events: 100m, 200m, 400m\nAge categories: U-12, U-16, U-20\nBring running shoes',
                'entry_fee' => '250',
                'required_documents' => json_encode(['Aadhaar Card', 'Age proof', 'Medical certificate']),
                'vacancies' => 100,
                'benefits' => 'Top performers selected for state team,Free track access for a month',
                'status' => 'published',
            ],
            [
                'name' => 'Basketball Skills Assessment',
                'posted_by_user_id' => 3,
                'academy_id' => null,
                'organization_name' => 'Hoop Dreams Academy',
                'sport_id' => 6,
                'event_datetime' => now()->addDays(25)->toDateTimeString(),
                'venue' => 'Kanteerava Indoor Stadium, Bangalore',
                'google_maps_url' => 'https://maps.google.com/?q=Kanteerava+Stadium',
                'city_id' => 4,
                'contact_number' => '+91 98111 44444',
                'registration_deadline' => now()->addDays(18)->toDateString(),
                'eligibility' => 'Age 10-20 years\nBasketball experience preferred\nBring basketball shoes',
                'entry_fee' => '350',
                'required_documents' => json_encode(['Aadhaar Card', 'School/college ID']),
                'vacancies' => 30,
                'benefits' => 'Free basketball jersey,Coaching assessment report',
                'status' => 'published',
            ],
            [
                'name' => 'Chess Grandmaster Workshop & Trials',
                'posted_by_user_id' => 3,
                'academy_id' => null,
                'organization_name' => 'Think Chess Academy',
                'sport_id' => 9,
                'event_datetime' => now()->addDays(15)->toDateTimeString(),
                'venue' => 'Science City Hall, Ahmedabad',
                'google_maps_url' => 'https://maps.google.com/?q=Science+City+Ahmedabad',
                'city_id' => 1,
                'contact_number' => '+91 98270 55555',
                'registration_deadline' => now()->addDays(10)->toDateString(),
                'eligibility' => 'All skill levels welcome\nAge 6-25 years\nChess set not required',
                'entry_fee' => '100',
                'required_documents' => json_encode(['Aadhaar Card']),
                'vacancies' => 60,
                'benefits' => 'GM workshop access,Analysis session with master',
                'status' => 'published',
            ],
            [
                'name' => 'U-18 Football Trials - Bangalore',
                'posted_by_user_id' => 3,
                'academy_id' => null,
                'organization_name' => 'Bangalore FC Youth Academy',
                'sport_id' => 2,
                'event_datetime' => now()->addDays(30)->toDateTimeString(),
                'venue' => 'Bangalore Football Stadium',
                'google_maps_url' => 'https://maps.google.com/?q=Bangalore+Football+Stadium',
                'city_id' => 4,
                'contact_number' => '+91 98111 66666',
                'registration_deadline' => now()->addDays(21)->toDateString(),
                'eligibility' => 'Boys aged 16-18 years\nFootball experience required\nCarry boots and shin guards',
                'entry_fee' => '400',
                'required_documents' => json_encode(['Aadhaar Card', 'School ID', 'Football experience certificate']),
                'vacancies' => 20,
                'benefits' => 'Selected players join academy team,Competition exposure',
                'status' => 'published',
            ],
        ];

        foreach ($trials as $trial) {
            Trial::updateOrCreate(
                ['name' => $trial['name']],
                $trial
            );
        }

        $this->command->info('Trials seeded: ' . count($trials));
    }
}
