// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeoKtwQmVQJP3KYKzDnd6CJeq82pvi0aw',
    appId: '1:241021895160:web:0251b5e57674f07875160d',
    messagingSenderId: '241021895160',
    projectId: 'sportx-8e0ec',
    authDomain: 'sportx-8e0ec.firebaseapp.com',
    storageBucket: 'sportx-8e0ec.firebasestorage.app',
    measurementId: 'G-7VVRFYZQ35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANAGtDLdE09WYVBHqILdnlcDq4TTNZQqo',
    appId: '1:241021895160:android:573433db273a249c75160d',
    messagingSenderId: '241021895160',
    projectId: 'sportx-8e0ec',
    storageBucket: 'sportx-8e0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdMZWur3Ib7iSeMW8pNEb1Hh2ne0gFyE',
    appId: '1:241021895160:ios:db9dcaccffd2d48e75160d',
    messagingSenderId: '241021895160',
    projectId: 'sportx-8e0ec',
    storageBucket: 'sportx-8e0ec.firebasestorage.app',
    iosBundleId: 'com.sportx.application',
  );
}
